name: Veracode Static Analysis
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: mvn -B package --file app/pom.xml
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          # Veracode application profile name
          appname: 'Verademo'
          createprofile: false
          # Veracode application sandbox name
          sandboxname: 'GitHub'
          createsandbox: false
          # Build artifact directory
          filepath: 'app/target/verademo.war'
          # Scan name
          version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          # API credentials
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scantimeout: 60
          # Optional arguments
          deleteincompletescan: 2
#         debug: true
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'


      # Docker version
      # - name: Veracode Upload and Scan using Docker
      #   uses: mosteo-actions/docker-run@v1
      #   with:
      #     image: veracode/api-wrapper-java:latest
      #     command: java -jar api-wrapper-java.jar -action Uploadandscan -filepath /app/target/verademo.war -vid=${{ secrets.VERACODE_API_ID }} -vkey=${{ secrets.VERACODE_API_KEY }} -appname Verademo -sandboxname GitHub -version ${{ github.buildNumber }} -deleteincompletescan 2
